version: 0.2
phases:
  install:
    runtime-verssions:
      nodejs: 14
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre build
      - npm install
  build:
    commands:
      - echo build
      - npm test
  post_build:
    commands:
      - echo post build
artifacts:
  files:
    - '**/*'
